export const userData = [
    {
        name:'Jan',
        "Active User": 1400,
    },
    {
        name:'Feb',
        "Active User": 3000,
    },
    {
        name:'Mar',
        "Active User": 3700,
    },
    {
        name:'Apr',
        "Active User": 3000,
    },
    {
        name:'May',
        "Active User": 2000,
    },
    {
        name:'Jun',
        "Active User": 3300,
    },
    {
        name:'Jul',
        "Active User": 3200,
    },
    {
        name:'Agu',
        "Active User": 2000,
    },
    {
        name:'Sep',
        "Active User": 1300,
    },
    {
        name:'Oct',
        "Active User": 2500,
    },
    {
        name:'Nov',
        "Active User": 3000,
    },
    {
        name:'Dec',
        "Active User": 4000,
    },
]

export const productData = [
    {
        name:'Jan',
        "Sales": 1400,
    },
    {
        name:'Feb',
        "Sales": 3000,
    },
    {
        name:'Mar',
        "Sales": 3700,
    },
]


export const userRows = [
    {   id: 1,
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 2, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 3, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 4, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 5, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 6, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 7, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 8, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 9, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 10, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 11, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },
    {   id: 12, 
        username: 'Jardel O Dut', 
        avatar: 'https://avatars.githubusercontent.com/u/26754111?v=4', 
        email: 'jardelduate594@gmail.com',
        status:'active',
        transaction: '$120.00',
    },

]


export const productsRows = [
    {   id: 1,
        name: 'Alexa echo dot 4', 
        img: 'https://m.media-amazon.com/images/I/714Rq4k05UL._AC_SY450_.jpg', 
        stock: 124,
        status:'active',
        price: '$60.00',
    },
    {   id: 2, 
        name: 'Google mini nest', 
        img: 'https://images.kabum.com.br/produtos/fotos/108078/google-smart-home-mini-preto-ga00781-br_google-smart-home-mini-preto-ga00781-br_1573567229_g.jpg', 
        stock: 124,
        status:'active',
        price: '$50.00',
    },
    {   id: 3, 
        name: 'Iphone 13', 
        img: 'https://www.fastshop.com.br//wcsstore/FastShopCAS/imagens/_AE_Apple/AEMLQ63BRAPTO/AEMLQ63BRAPTO_PRD_447_1.jpg', 
        stock: 124,
        status:'active',
        price: '$1200.00',
    },
    {   id: 4, 
        name: 'Playstation 5', 
        img: 'https://images.kabum.com.br/produtos/fotos/sync_mirakl/181395/Console-Playstation-5-825GB-PS5-_1643893529_g.jpg', 
        stock: 124,
        status:'active',
        price: '$900.00',
    },
    {   id: 5, 
        name: 'Samsung Watch 4', 
        img: 'https://samsungbr.vtexassets.com/arquivos/ids/336529-800-auto?width=800&height=auto&aspect=true', 
        stock: 124,
        status:'active',
        price: '$300.00',
    },
    {   id: 6, 
        name: 'Notebook Dell G7', 
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQImjWi5YEjy0n81MPugXyzdpySrLkPnDV-EnO3lSzPLTmtvO416MHqyjZLSQMxDAxFTHg&usqp=CAU', 
        stock: 124,
        status:'active',
        price: '$1000.00',
    },

    {   id: 7, 
        name: 'Headset Beats Studio 3', 
        img: 'https://www.fastshop.com.br//wcsstore/FastShopCAS/imagens/_AD_Audio/AEMXJA2LLAPTO/AEMXJA2LLAPTO_PRD_447_4.jpg', 
        stock: 124,
        status:'active',
        price: '$300.00',
    },
    {   id: 8, 
        name: 'Headset Ryzer Nari Ultimate', 
        img: 'https://images.kabum.com.br/produtos/fotos/108519/headset-gamer-razer-nari-ultimate-for-xbox-one-drivers-50mm-rz04-02910100-r3u1-_1576769617_gg.jpg', 
        stock: 124,
        status:'active',
        price: '$110.00',
    },
    {   id: 9, 
        name: 'Monitor Dell ', 
        img: 'https://i.dell.com/is/image/DellContent//content/dam/ss2/product-images/peripherals/output-devices/dell/monitors/up2720q/global-spi/ng/up2720q_cfp_00000ff000_gy_4000x3000.jpg?fmt=pjpg&pscan=auto&scl=1&hei=402&wid=475&qlt=100,0&resMode=sharp2&size=475,402', 
        stock: 124,
        status:'active',
        price: '$490.00',
    },
    {   id: 10, 
        name: 'Notebook Razer 17', 
        img: 'https://assets.razerzone.com/eeimages/products/26727/rzrblade14-16.png', 
        stock: 124,
        status:'active',
        price: '$3000.00',
    },
    {   id: 11, 
        name: 'VR Glasses', 
        img: 'https://img.joomcdn.net/c929b8e24236a43ed09cd221d3b946027ce942df_original.jpeg', 
        stock: 124,
        status:'active',
        price: '$1200.00',
    },

]